# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Build arguments
ARG OS=MACOS
ARG IDE=ANTIGRAVITY
ARG MODEL=GEMINI

# Set environment variables from build args
ENV OS=${OS}
ENV IDE=${IDE}
ENV MODEL=${MODEL}

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev

WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir .

# Expose port if server uses it, although MCP might use stdio

# Command to run the MCP server
CMD ["python", "-m", "src.ableton_mcp.server"]
